### ISSUE TITLE
Need help (Error exit code 1)

### ISSUE THREAD

**Issue by HaiziIzzudin** [sitek94/vite-deploy-demo#7]
I don't know what caused it. I think I have write imports into the main.js file.

``` md
> delete-life-2@0.0.0 build
> vite build

vite v5.0.2 building for production...
transforming...
✓ 3 modules transformed.
[vite]: Rollup failed to resolve import "@material/web/button/filled-button.js" from "/home/runner/work/delete-life/delete-life/main.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@material/web/button/filled-button.js" from "/home/runner/work/delete-life/delete-life/main.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///home/runner/work/delete-life/delete-life/node_modules/vite/dist/node/chunks/dep-ErEj4WmL.js:65228:27)
    at onRollupWarning (file:///home/runner/work/delete-life/delete-life/node_modules/vite/dist/node/chunks/dep-ErEj4WmL.js:65256:9)
    at onwarn (file:///home/runner/work/delete-life/delete-life/node_modules/vite/dist/node/chunks/dep-ErEj4WmL.js:64973:13)
    at file:///home/runner/work/delete-life/delete-life/node_modules/rollup/dist/es/shared/node-entry.js:17333:13
    at Object.logger [as onLog] (file:///home/runner/work/delete-life/delete-life/node_modules/rollup/dist/es/shared/node-entry.js:18994:9)
    at ModuleLoader.handleInvalidResolvedId (file:///home/runner/work/delete-life/delete-life/node_modules/rollup/dist/es/shared/node-entry.js:17937:26)
    at file:///home/runner/work/delete-life/delete-life/node_modules/rollup/dist/es/shared/node-entry.js:17895:26
```

Please let me know if you want to know the project more in detail.

**Comment by sitek94** [comment]
I'm not sure, can you send link to your repo?
